plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_262_version}"
	id 'maven-publish'
}

version = project.fabric_262_mod_version
group = rootProject.maven_group

base {
	archivesName = "${rootProject.archives_base_name}-fabric-26.2"
}

repositories {
	maven {
		url = "https://pkgs.dev.azure.com/djtheredstoner/DevAuth/_packaging/public/maven/v1"
		content {
			includeGroup("me.djtheredstoner")
		}
	}

	maven { url = "https://api.modrinth.com/maven" }
	maven { url = "https://maven.terraformersmc.com/" }
}

loom {
	splitEnvironmentSourceSets()
}

sourceSets {
	main {
		resources.srcDir(project(":common").file("src/main/resources"))
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.fabric_262_minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.fabric_262_loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_262_fabric_api_version}"

	implementation project(":common")

	String lwjglVersion = "3.4.1"
	implementation "org.lwjgl:lwjgl-nfd:${lwjglVersion}"
	include "org.lwjgl:lwjgl-nfd:${lwjglVersion}"
	include "org.lwjgl:lwjgl-nfd:${lwjglVersion}:natives-windows"
	include "org.lwjgl:lwjgl-nfd:${lwjglVersion}:natives-windows-arm64"
	include "org.lwjgl:lwjgl-nfd:${lwjglVersion}:natives-linux"
	include "org.lwjgl:lwjgl-nfd:${lwjglVersion}:natives-linux-arm64"
	include "org.lwjgl:lwjgl-nfd:${lwjglVersion}:natives-macos"
	include "org.lwjgl:lwjgl-nfd:${lwjglVersion}:natives-macos-arm64"

	implementation "org.lwjgl:lwjgl-assimp:${lwjglVersion}"
	include "org.lwjgl:lwjgl-assimp:${lwjglVersion}"
	include "org.lwjgl:lwjgl-assimp:${lwjglVersion}:natives-windows"
	include "org.lwjgl:lwjgl-assimp:${lwjglVersion}:natives-windows-arm64"
	include "org.lwjgl:lwjgl-assimp:${lwjglVersion}:natives-linux"
	include "org.lwjgl:lwjgl-assimp:${lwjglVersion}:natives-linux-arm64"
	include "org.lwjgl:lwjgl-assimp:${lwjglVersion}:natives-macos"
	include "org.lwjgl:lwjgl-assimp:${lwjglVersion}:natives-macos-arm64"

	include implementation("de.javagl:jgltf-model:2.0.4")
	include implementation("de.javagl:jgltf-impl-v2:2.0.4")

	runtimeOnly "me.djtheredstoner:DevAuth-fabric:1.2.2"
	runtimeOnly "org.lwjgl:lwjgl-nfd:${lwjglVersion}:natives-windows"
	runtimeOnly "org.lwjgl:lwjgl-nfd:${lwjglVersion}:natives-windows-arm64"
	runtimeOnly "org.lwjgl:lwjgl-nfd:${lwjglVersion}:natives-linux"
	runtimeOnly "org.lwjgl:lwjgl-nfd:${lwjglVersion}:natives-linux-arm64"
	runtimeOnly "org.lwjgl:lwjgl-nfd:${lwjglVersion}:natives-macos"
	runtimeOnly "org.lwjgl:lwjgl-nfd:${lwjglVersion}:natives-macos-arm64"
	runtimeOnly "org.lwjgl:lwjgl-assimp:${lwjglVersion}:natives-windows"
	runtimeOnly "org.lwjgl:lwjgl-assimp:${lwjglVersion}:natives-windows-arm64"
	runtimeOnly "org.lwjgl:lwjgl-assimp:${lwjglVersion}:natives-linux"
	runtimeOnly "org.lwjgl:lwjgl-assimp:${lwjglVersion}:natives-linux-arm64"
	runtimeOnly "org.lwjgl:lwjgl-assimp:${lwjglVersion}:natives-macos"
	runtimeOnly "org.lwjgl:lwjgl-assimp:${lwjglVersion}:natives-macos-arm64"
	implementation "maven.modrinth:modmenu:${project.fabric_262_modmenu_version}"
}

jar {
	archiveFileName.set("${rootProject.archives_base_name}-v${project.version}+mc${project.fabric_262_minecraft_version}.jar")
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": inputs.properties.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	dependsOn(":common:classes")
	inputs.property "archivesName", project.base.archivesName

	from(project(":common").sourceSets.main.output.classesDirs)

	from(rootProject.file("LICENSE")) {
		rename { "${it}_${inputs.properties.archivesName}"}
	}
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.base.archivesName.get()
			from components.java
		}
	}

	repositories {
	}
}
